- name: Installing the Package
  ansible.builtin.package:
    name: nginx
    state: present

- name: Copy and extract the file on remote machine
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes
  
- name: remove the file in {{COMPONENT}}
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: copying the file from source to {{COMPONENT}}
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/static/
    dest: /usr/share/nginx/html
    remote_src: yes