pipeline{
    agent any
    stages{
        stage("First Stage") {
           steps{
            echo "Welcome to jenkins pipeline"
           }       
        }
        stage("Second stage") {
           steps{
            echo " this is Second stage"
           }
        }
        stage("Third stage") {
           steps{
            echo "this is third stage"
           }
        }
    }
}