pipeline{
    agent any
    stages{
        stage(First stage) {
           steps{
            echo "Welcome to jenkins pipeline"
           }       
        }
        stage(Second stage) {
           steps{
            echo " this is Second stage"
           }
        }
        stage(Third stage) {
           steps{
            echo "this is third stage"
           }
        }
    }
}