- name: gathering the kernal
  hosts: slave
  become: true
  gather_facts: true
  vars_prompt:
   - name: update_confirmation
     prompt: "Security updates are available. Update all packages (y/N)?"
     default: n
     private: no
  tasks:
   - name: kernal version
     ansible.builtin.debug:
       msg: OS version is {{ansible_distribution}}.{{ansible_distribution_version}} and kernal version is {{ansible_kernel}}
      
   - name: checking kernel updates
     ansible.builtin.yum:
       list: updates
     register: yumoutput

   - name: Listing the yum updates
     ansible.builtin.debug:
       msg: "{{ yumoutput | json_query(my_query) }}"
     vars:
       my_query: "results[].{name: name, repo: repo, version: version}"

   - name: checking kernel updates
     ansible.builtin.yum:
       name: 
        - nginx
        - httpd
        - mysql
        - php
        - mysql
       state: present
     when: update_confirmation == "y"
     register: package_result

   - name: Current packages are getting installing
     ansible.builtin.debug:
       msg: Kernal updates are getting installing {{package_result.results | json_query(my_query) }}
     vars:
       my_query: "results[].{Installed: Installed}"
    
   

   