- name: gathering the kernal
  hosts: slave
  become: true
  gather_facts: true
  vars_prompt:
   - name: update_confirmation
     prompt: "Security updates are available. Update all packages (y/N)?"
     default: n
     private: no
  tasks:
   - name: kernal version
     ansible.builtin.debug:
       msg: OS version is {{ansible_distribution}}.{{ansible_distribution_version}} and kernal version is {{ansible_kernel}}
      
   

   - name: checking kernel updates
     ansible.builtin.yum:
       name: 
        - nginx
        - httpd
        - mysql
        - php
        - mysql
       state: latest
     when: update_confirmation == "y"
     register: package_result

   - name: Current packages are getting installing
     ansible.builtin.debug:
       msg: Kernal updates are getting installing {{package_result.results| lsit }}
    
   

   