- name: gathering the kernal
  hosts: all
  gather_facts: true
  tasks:
   - name: kernal version
     ansible.builtin.debug:
       msg: "{{ansible_kernel}}"
      
    - name: checking kernel updates
      ansible.builtin.command: yum check-update
      remote_server: yes