- name: gathering the kernal
  hosts: all
  become: true
  gather_facts: true
  tasks:
   vars_prompt:
    - name: update_confirmation
      prompt: "Security updates are available. Update all packages (y/N)?"
      default: n

   - name: kernal version
     ansible.builtin.debug:
       msg: OS version is {{ansible_distribution}}.{{ansible_distribution_version}} and kernal version is {{ansible_kernel}}
      
   - name: checking kernel updates
     ansible.builtin.yum:
       list: updates
     register: yumoutput

   - name: Listing the yum updates
     ansible.builtin.debug:
       msg: "{{ yumoutput | json_query(my_query) }}"
     vars:
       my_query: "results[].{name: name, version: version, repo: repo}"

   - name: checking kernel updates
     ansible.builtin.yum:
       name: *
       state: latest
       when: update_confirmation == "y"
    
   

   