- name: Package installation demo
  hosts: all
  become: true
  tasks: 
   - name: Installing the Package
     ansible.builtin.package:
       name: nginx
       state: present
      ansible.builtin.debug:
        msg: {{package}}

   - name: Installing multiple packages
     ansible.builtin.package:
       name:
         - httpd
         - mariadb-server
       state: present