- name: Package installation demo
  hosts: all
  become: true
  tasks: 
   - name: Installing the Package
     ansible.builtin.package:
       name: nginx
       state: present
   - name: Package install output
     ansible.builtin.debug:
        msg: {{nginx}}

   - name: Installing multiple packages
     ansible.builtin.package:
       name:
         - httpd
         - mariadb-server
       state: present