- name: gathering the bullikaya
  hosts: all
  tasks:
   - name: gathering the facts
     service_facts:
     ansible.builtin.debug: 
       msg: "{{ ansible_facts.services | dict2items 
          | selectattr('value.state', '==', 'running') | items2dict }}"
      
  