- name: gathering the servicefacts
  hosts: all
  tasks:
   - name: gathering the facts
     service_facts:

   - name: pritning the service status
     ansible.builtin.debug:
       msg: "{{ ansible_facts.services }}"| regex_findall('.*state running.*')

  
       
  