- name: Demo of using shell with ansible
  hosts: all
  tasks:
    - name: Runninguptime 
       ansible.bulitin.shell: uptime
       register: OUT

    - name: Printing uptime
       ansible.bulitin.debug:
        msg: "uptime is {{OUT.stdout}}"