- name: Demo of using shell with ansible
  hosts: all
  tasks:
    - name: run uptime command
      ansible.builtin.shell: uptime
      register: OUT

    - name: Printing uptime
      ansible.bulitin.debug:
        msg: "uptime is {{OUT}}"