- name: Copying the file {{COMPONENT}}
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing the Package {{COMPONENT}}
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: Replacing the string in {{COMPONENT}}
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: starting the service {{COMPONENT}}
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: mongod
    daemon_reload: true1
  