- name: Copying the file roboshop
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing the Package {{COMPONENT}}
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: starting the service {{COMPONENT}}
  ansible.builtin.systemd_service:
    state: restarted
    enabled: true
    name: mongod
    daemon_reload: true